### ISSUE TITLE
Katacoda Support - Environments for DotNet

### ISSUE THREAD

**Issue by BenHall** [tinytech-delivery/katacoda-scenarios#2]
Hello,

Great to see you starting to build Katacoda content. If we can be of any help then please do let us know.

I noticed you had a problem with using the dotnet image id. This was an issue on our side and has now been corrected. @merbla  Please use `"imageid": "dotnet"` within the index.json as with your first commit.

Please let me know if we can be of any more assistance.

Ben

**Comment by merbla** [comment]
Hi @BenHall,

I will update the `index.json` and recommit under a new scenario.  Just wondering if there will be a dotnet core 2 e.g. `microsoft/dotnet:2-sdk` image soon?

The product is great BTW!

**Comment by BenHall** [comment]
Good suggestion! If you need 2.0 then let us know, we'll update the image soon.

**Comment by merbla** [comment]
@BenHall what is the best combo, given the current features of KataCoda?

I am looking for:

* `dotnet core 2` with SDK 
* Terminal & editor features
* Ability to copy assets for bootstrapping scenarios.

Currently I have reverted to the Ubuntu image and installing dotnet core 2.

Any thoughts/suggestions?

**Comment by merbla** [comment]
Hey @BenHall,

Just wondering if there are updated versions of KataCoda Images for DotNet Core?

**Comment by BenHall** [comment]
FYI: We upgraded to DotNet 2.1 when it was released a couple of weeks ago.

**Comment by merbla** [comment]
Thanks @BenHall
